name: ci

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Installations (should hit cache)
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.14.1
          vessel-version: 0.6.4

      # Type check
      - name: "check"
        run:
          make check-strict
      # Tests
      - name: "test"
        run: make test
      # Make docs
      - name: "docs"
        run: make docs